//
// Created by jverdesi on 12/25/22.
//

#ifndef ADVENTOFCODE22_PROBOSCIDEAVOLCANIUM_H
#define ADVENTOFCODE22_PROBOSCIDEAVOLCANIUM_H


int mainDay16();


#endif //ADVENTOFCODE22_PROBOSCIDEAVOLCANIUM_H
