//
// Created by jacob on 12/3/2022.
//

#ifndef ADVENTOFCODE22_RUCKSACKREORGANIZATION_H
#define ADVENTOFCODE22_RUCKSACKREORGANIZATION_H


int mainDay3();


#endif //ADVENTOFCODE22_RUCKSACKREORGANIZATION_H
